spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Extra
car.validation.url=http://localhost:8083/car-validation/validate
audit.service.url=http://localhost:8084/audit/log
# Eureka
#eureka client properties
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=false
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# Swagger + security
keycloak.issuer=http://localhost:8080/realms/master
keycloak.realm=master
springdoc.swagger-ui.server-url=http://localhost:9091
springdoc.swagger-ui.server[0].url=http://localhost:9091
springdoc.swagger-ui.server[0].description=Router Gateway
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/master/protocol/openid-connect/certs

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# INTERNAL SERVICE AUTH
keycloak.token-url=http://localhost:8080/realms/master/protocol/openid-connect/token
keycloak.client-id=car-service-client
keycloak.client-secret=m8fpF75jhC1CWYKncJyslwI444OIH8bx

# USER SERVICE URL
user.service.url=http://localhost:8082







